const scs_input_device_input_t inputs[] = {
    {"steering", "ETS2LA Steering", SCS_VALUE_TYPE_float},
    {"aforward", "ETS2LA Forward", SCS_VALUE_TYPE_float},
    {"abackward", "ETS2LA Backward", SCS_VALUE_TYPE_float},
    {"clutch", "ETS2LA Clutch", SCS_VALUE_TYPE_float},
    {"pause", "ETS2LA Pause", SCS_VALUE_TYPE_bool},
    {"parkingbrake", "ETS2LA Parking Brake", SCS_VALUE_TYPE_bool},
    {"wipers", "ETS2LA Wipers", SCS_VALUE_TYPE_bool},
    {"cruiectrl", "ETS2LA Cruise Control", SCS_VALUE_TYPE_bool},
    {"cruiectrlinc", "ETS2LA Cruise Control Increase", SCS_VALUE_TYPE_bool},
    {"cruiectrldec", "ETS2LA Cruise Control Decrease", SCS_VALUE_TYPE_bool},
    {"cruiectrlres", "ETS2LA Cruise Control Reset", SCS_VALUE_TYPE_bool},
    {"light", "ETS2LA Lights", SCS_VALUE_TYPE_bool},
    {"hblight", "ETS2LA High Beams", SCS_VALUE_TYPE_bool},
    {"lblinker", "ETS2LA Left (toggle) Blinker", SCS_VALUE_TYPE_bool},
    {"rblinker", "ETS2LA Right (toggle) Blinker", SCS_VALUE_TYPE_bool},
    {"lblinkerh", "ETS2LA Left (hold) Blinker", SCS_VALUE_TYPE_bool},
    {"rblinkerh", "ETS2LA Right (hold) Blinker", SCS_VALUE_TYPE_bool},
    {"quickpark", "ETS2LA Quickpark", SCS_VALUE_TYPE_bool},
    {"drive", "ETS2LA Drive", SCS_VALUE_TYPE_bool},
    {"reverse", "ETS2LA Reverse", SCS_VALUE_TYPE_bool},
    {"cycl_zoom", "ETS2LA Cycle Zoom", SCS_VALUE_TYPE_bool},
    {"tripreset", "ETS2LA Reset Trip", SCS_VALUE_TYPE_bool},
    {"wipersback", "ETS2LA Rear Wipers", SCS_VALUE_TYPE_bool},
    {"wipers0", "ETS2LA Wiper LVL 0", SCS_VALUE_TYPE_bool},
    {"wipers1", "ETS2LA Wiper LVL 1", SCS_VALUE_TYPE_bool},
    {"wipers2", "ETS2LA Wiper LVL 2", SCS_VALUE_TYPE_bool},
    {"wipers3", "ETS2LA Wiper LVL 3", SCS_VALUE_TYPE_bool},
    {"wipers4", "ETS2LA Wiper LVL 4", SCS_VALUE_TYPE_bool},
    {"horn", "ETS2LA Horn", SCS_VALUE_TYPE_bool},
    {"airhorn", "ETS2LA Airhorn", SCS_VALUE_TYPE_bool},
    {"lighthorn", "ETS2LA Light Horn", SCS_VALUE_TYPE_bool},
    {"cam1", "ETS2LA Camera 1", SCS_VALUE_TYPE_bool},
    {"cam2", "ETS2LA Camera 2", SCS_VALUE_TYPE_bool},
    {"cam3", "ETS2LA Camera 3", SCS_VALUE_TYPE_bool},
    {"cam4", "ETS2LA Camera 4", SCS_VALUE_TYPE_bool},
    {"cam5", "ETS2LA Camera 5", SCS_VALUE_TYPE_bool},
    {"cam6", "ETS2LA Camera 6", SCS_VALUE_TYPE_bool},
    {"cam7", "ETS2LA Camera 7", SCS_VALUE_TYPE_bool},
    {"cam8", "ETS2LA Camera 8", SCS_VALUE_TYPE_bool},
    {"mapzoom_in", "ETS2LA Zoom Map In", SCS_VALUE_TYPE_bool},
    {"mapzoom_out", "ETS2LA Zoom Map Out", SCS_VALUE_TYPE_bool},
    {"accmode", "ETS2LA ACC Mode", SCS_VALUE_TYPE_bool},
    {"showmirrors", "ETS2LA Show Mirrors", SCS_VALUE_TYPE_bool},
    {"flasher4way", "ETS2LA Hazard Lights", SCS_VALUE_TYPE_bool},
    {"activate", "ETS2LA Activate", SCS_VALUE_TYPE_bool},
    {"assistact1", "ETS2LA Assist Act 1", SCS_VALUE_TYPE_bool},
    {"assistact2", "ETS2LA Assist Act 2", SCS_VALUE_TYPE_bool},
    {"assistact3", "ETS2LA Assist Act 3", SCS_VALUE_TYPE_bool},
    {"assistact4", "ETS2LA Assist Act 4", SCS_VALUE_TYPE_bool},
    {"assistact5", "ETS2LA Assist Act 5", SCS_VALUE_TYPE_bool},
};
